import { promises as fs } from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import type { Plugin, ResolvedConfig, ViteDevServer } from "vite";
import { normalizePath } from "vite";

interface IconsPluginOptions {
  iconsDir?: string;
  outputFile?: string;
  case?: "kebab" | "camel";
  failOnDuplicate?: boolean;
  debounceMs?: number;
  includeSubdirsInName?: boolean;
  exportName?: string;
}

interface GenerateResult {
  changed: boolean;
  content: string;
  count: number;
}

export function icons(options: IconsPluginOptions = {}): Plugin {
  const {
    iconsDir = "src/assets/icons",
    outputFile = "src/components/icons/icons.generated.ts",
    case: nameCase = "camel",
    failOnDuplicate = true,
    debounceMs = 80,
    includeSubdirsInName = true,
    exportName = "icons",
  } = options;

  let config: ResolvedConfig;
  let server: ViteDevServer | null = null;
  let lastHash: string | null = null;
  let debounceTimer: ReturnType<typeof setTimeout> | null = null;
  let pendingRun: Promise<void> | null = null;

  const SVG_EXT_RE = /\.svg$/i;
  const WHITESPACE_RE = /[\s_]+/g;
  const INVALID_IDENT_RE = /[^a-zA-Z0-9$_-]+/g;

  function toCamelCase(value: string): string {
    return value
      .toLowerCase()
      .replace(/[-_\s/\\]+([a-zA-Z0-9])/g, (_, char: string) =>
        char.toUpperCase(),
      )
      .replace(/^[A-Z]/, (m) => m.toLowerCase());
  }

  function toKebabCase(value: string): string {
    return value
      .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
      .replace(/[/\\]+/g, "-")
      .replace(WHITESPACE_RE, "-")
      .replace(INVALID_IDENT_RE, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "")
      .toLowerCase();
  }

  function sanitizeName(raw: string): string {
    const withoutExt = raw.replace(SVG_EXT_RE, "");
    const normalizedPath = normalizePath(withoutExt);
    const source = includeSubdirsInName
      ? normalizedPath
      : path.posix.basename(normalizedPath);

    const normalized =
      nameCase === "camel" ? toCamelCase(source) : toKebabCase(source);

    const safe = normalized.replace(INVALID_IDENT_RE, "");
    if (!safe) {
      throw new Error(`[icons] Failed to derive icon name from "${raw}"`);
    }

    if (/^\d/.test(safe)) {
      return nameCase === "camel" ? `icon${safe}` : `icon-${safe}`;
    }

    return safe;
  }

  function hash(content: string): string {
    return crypto.createHash("sha1").update(content).digest("hex");
  }

  async function fileExists(filePath: string): Promise<boolean> {
    try {
      await fs.access(filePath);
      return true;
    } catch {
      return false;
    }
  }

  async function walkSvgFiles(dir: string): Promise<string[]> {
    if (!(await fileExists(dir))) return [];

    const entries = await fs.readdir(dir, { withFileTypes: true });
    const files = await Promise.all(
      entries.map(async (entry) => {
        const fullPath = path.resolve(dir, entry.name);

        if (entry.isDirectory()) {
          return walkSvgFiles(fullPath);
        }

        if (entry.isFile() && SVG_EXT_RE.test(entry.name)) {
          return [fullPath];
        }

        return [];
      }),
    );

    return files.flat();
  }

  function asObjectKey(key: string): string {
    return /^[$A-Z_][0-9A-Z_$]*$/i.test(key) ? key : JSON.stringify(key);
  }

  function createModuleContent(entries: Array<[string, string]>): string {
    const lines = entries.map(
      ([name, relPath]) =>
        `  ${asObjectKey(name)}: ${JSON.stringify(relPath)},`,
    );

    return `/* eslint-disable */
// Auto-generated by vite-plugin-icons-extended. Do not edit manually.

export const ${exportName} = {
${lines.join("\n")}
} as const;

export type IconName = keyof typeof ${exportName};
`;
  }

  async function writeFileAtomic(
    filePath: string,
    content: string,
  ): Promise<void> {
    const dir = path.dirname(filePath);
    const tempFile = path.join(
      dir,
      `.${path.basename(filePath)}.${process.pid}.tmp`,
    );

    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(tempFile, content, "utf8");
    await fs.rename(tempFile, filePath);
  }

  async function generate(): Promise<GenerateResult> {
    const root = config.root;
    const iconsPath = path.resolve(root, iconsDir);
    const outputPath = path.resolve(root, outputFile);

    const svgFiles = await walkSvgFiles(iconsPath);
    const namesMap = new Map<string, string>();

    for (const absFile of svgFiles) {
      const relFromIconsDir = normalizePath(path.relative(iconsPath, absFile));
      const iconName = sanitizeName(relFromIconsDir);

      const previous = namesMap.get(iconName);
      if (previous) {
        const message =
          `[icons] Duplicate icon name "${iconName}"\n` +
          `- ${previous}\n` +
          `- ${relFromIconsDir}`;

        if (failOnDuplicate) {
          throw new Error(message);
        }

        config.logger.warn(message);
        continue;
      }

      namesMap.set(iconName, relFromIconsDir);
    }

    const sortedEntries = [...namesMap.entries()].sort(([a], [b]) =>
      a.localeCompare(b),
    );

    const content = createModuleContent(sortedEntries);
    const nextHash = hash(content);

    if (nextHash === lastHash) {
      return { changed: false, content, count: sortedEntries.length };
    }

    lastHash = nextHash;
    await writeFileAtomic(outputPath, content);

    return { changed: true, content, count: sortedEntries.length };
  }

  async function runGeneration(reason: string): Promise<void> {
    if (pendingRun) {
      await pendingRun;
      return;
    }

    pendingRun = (async () => {
      try {
        const result = await generate();

        if (result.changed) {
          config.logger.info(
            `[icons] Generated ${result.count} icons (${reason})`,
            { timestamp: true },
          );
        }
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);

        if (config.command === "build") {
          throw error;
        }

        config.logger.error(message);
      } finally {
        pendingRun = null;
      }
    })();

    await pendingRun;
  }

  function scheduleGeneration(reason: string): void {
    if (debounceTimer) {
      clearTimeout(debounceTimer);
    }

    debounceTimer = setTimeout(() => {
      void runGeneration(reason);
    }, debounceMs);
  }

  function isInsideIconsDir(file: string): boolean {
    const target = normalizePath(path.resolve(config.root, iconsDir));
    const current = normalizePath(path.resolve(file));
    return current === target || current.startsWith(`${target}/`);
  }

  function isSvgFile(file: string): boolean {
    return SVG_EXT_RE.test(file);
  }

  return {
    name: "vite-plugin-icons",
    enforce: "pre",

    configResolved(resolvedConfig) {
      config = resolvedConfig;
    },

    async buildStart() {
      await runGeneration("buildStart");
    },

    configureServer(_server) {
      server = _server;
      const watchTarget = path.resolve(config.root, iconsDir);
      server.watcher.add(watchTarget);
    },

    async handleHotUpdate(ctx) {
      if (!isInsideIconsDir(ctx.file) || !isSvgFile(ctx.file)) {
        return;
      }

      scheduleGeneration(`hot-update:${path.basename(ctx.file)}`);
      return [];
    },

    async closeBundle() {
      if (debounceTimer) {
        clearTimeout(debounceTimer);
        debounceTimer = null;
      }
      server = null;
    },
  };
}
