/* eslint-disable */
// Auto-generated by vite-plugin-icons-extended. Do not edit manually.

export const icons = {
  basket: "basket.svg",
  cup: "cup.svg",
  profile: "profile.svg",
  "qr-code": "qr-code.svg",
} as const;

export type IconName = keyof typeof icons;
